### ISSUE TITLE
Variation component listens to changes in source src

### ISSUE THREAD

**Issue by sreenathnair** [ebi-webcomponents/protvista-variation#2]
It would be an ideal requirement to have the variation component listens to changes in source src attribute and repaint the component for that source.

**Comment by aurel-l** [comment]
I don't think it should care about where the data is coming from.
If the source's src attribute changes, it should be the data-loader's job to emit a new load event with the data. This component should just listen for new load events being emitted and react to those.

**Comment by aurel-l** [comment]
Yes, I believe there's already the logic to do that [here](https://github.com/ebi-webcomponents/protvista-variation/blob/master/src/protvista-variation.js#L101)
I added this needed change in the todo section of the [data-loader readme](https://github.com/ebi-webcomponents/data-loader/blob/master/README.md#to-do)

**Comment by xwatkins** [comment]
Ok great, I'll close this issue then. Planning on making this component inherit from `protvista-track` at some point which I think has the same listener.
